### ISSUE TITLE
Drop support for ocrd_kraken?

### ISSUE THREAD

**Issue by kba** [OCR-D/ocrd_all#11]
It's currently de-facto unmaintained and depends on an older version of kraken which depends on clstm which is a PITA to build.

We could re-enable it if/once ocrd_kraken has been updated.

**Comment by cneud** [comment]
+1

**Comment by bertsky** [comment]
> It's currently de-facto unmaintained and depends on an older version of kraken which depends on clstm which is a PITA to build.

Yes, but we _have_ a working recipe to build it here, which makes it easier to work ourselves upwards incrementally.

> We could re-enable it if/once ocrd_kraken has been updated.

What exactly are you proposing – to remove the subrepo (and its build deps and rules) entirely, or to remove `ocrd-kraken-binarize` (which is actually less than what `ocrd-cis-ocropy-binarize` provides) and `ocrd-kraken-segment` (which only works on the page level, only gives a full-page dummy region, and only gives bboxes for textlines) from `OCRD_EXECUTABLES` temporarily?

**Comment by kba** [comment]
> to remove the subrepo (and its build deps and rules) entirely

Yes. If we do this in a single commit, it will be easy to revert once/if we decide to work on ocrd_kraken again.

**Comment by bertsky** [comment]
> > to remove the subrepo (and its build deps and rules) entirely
> 
> Yes. If we do this in a single commit, it will be easy to revert once/if we decide to work on ocrd_kraken again.

I see. Well I'm afraid it won't be as simple as that, because build rules keep evolving systematically (and the removed components won't be dragged along).

But I am not saying I am against that entirely. Just now is not a good moment: I am in the middle of a PR that will bring module-selective build rules, optional installation in editable mode and predefined selections for Docker images. Hooking into module-specific venvs/Dockers will be next. (After that, I would be fine with removing ocrd_kraken.)

**Comment by kba** [comment]
> I am in the middle of a PR that will bring module-selective build rules, optional installation in editable mode and predefined selections for Docker images. Hooking into module-specific venvs/Dockers will be next.

Cool, looking forward.

> (After that, I would be fine with removing ocrd_kraken.)

Fine with me, we should document it. Exclude it from the `DOCKER_MODULES` like `opencv-python`?

**Comment by bertsky** [comment]
> Exclude it from the `DOCKER_MODULES` like `opencv-python`?

I thought you wanted to remove it entirely?

Until then, no, I now use `OCRD_MODULES` as a general way for filtering all rules, including `docker` (in its various tags/targets). Just cannot run through all tests as long as #15 is in the way.

**Comment by kba** [comment]
>> Exclude it from the DOCKER_MODULES like opencv-python?

> I thought you wanted to remove it entirely?

I do but I don't want to interfere with your upcoming work. This seemed like a simple hack. We can just document that people shouldn't use ocrd_kraken even though it's included.

**Comment by bertsky** [comment]
> I do but I don't want to interfere with your upcoming work. This seemed like a simple hack. We can just document that people shouldn't use ocrd_kraken even though it's included.

Oh, right: in the meantime, if you want to produce docker images already, yes, passing `DOCKER_MODULES` is the way to go. I have used the following for a medium image so far:

```sh
make docker DOCKER_MODULES="cor-asv-ann core dinglehopper format-converters ocrd_calamari ocrd_cis ocrd_im6convert ocrd_keraslm ocrd_olena ocrd_segment ocrd_tesserocr tesseract tesserocr workflow-configuration"
```

**Comment by bertsky** [comment]
How about deactivating this via the same [mechanism](https://github.com/OCR-D/ocrd_all/blob/bcbf7b99d2f7fa690dfe863e5237f7a1d7178d54/Makefile#L42) like `cor-asv-fst`?

**Comment by stweil** [comment]
Good idea, but we should not make that line longer and longer. I suggest this pattern:

    DISABLED_MODULES :=
    DISABLED_MODULES += cor-asv-fst
    DISABLED_MODULES += opencv-python
    # Add more modules which are disabled in the default configuration like that.
    ifeq ($(strip $(OCRD_MODULES)),)
    override OCRD_MODULES := $(filter-out $(DISABLED_MODULES),$(shell git submodule status | while read commit dir ref; do echo $$dir; done))
    endif

**Comment by bertsky** [comment]
True. Perhaps using `?=` instead of `:=` to allow passing in from the shell environment.

**Comment by kba** [comment]
> Perhaps using ?= instead of := to allow passing in from the shell environment.

Difference between ?= and := is variable interpolation with the latter only interpolated once at assignment. They can both be overridden from the shell environment.

**Comment by kba** [comment]
```
DISABLED_MODULES :=
```

We should really remove ocrd_ocropy (redundant and obsolete) and ocrd_kraken (largely unmaintained) not just disable them. But in the meantime this is a clean solution and allows for blacklisting in addition to whitelisting via `OCRD_MODULES`.

**Comment by bertsky** [comment]
> Difference between ?= and := is variable interpolation with the latter only interpolated once at assignment. 

Yes, but the second difference is that `?=` does not override variables from the shell environment, whreas `:=` does.

> They can both be overridden from the shell environment.

You probably mean _command arguments_ (`make var=val`), not _shell environment variables_ (`var=val make`)?

**Comment by kba** [comment]
> You probably mean command arguments (make var=val), not shell environment variables (var=val make)?

I did mean environement variables but you're right. `:=` and `=` assigned variables won't be overridden from environment variables, only those from `?=`. "command arguments" should always override assignments.
