### ISSUE TITLE
add CI test with full realistic workflow on sample data

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd_all#112]
Most submodules are CI-tested individually. So when we make a new release here, as long as we don't negligently integrate failed versions, we can feel better with each update.

However, there are still two classes of errors which will evade this scheme:
1. within-module regressions not covered by their automatic unit tests
2. cross-module regressions (i.e. unmet implicit interdependencies between versions)

For the latter, we could reduce our risk by introducing workflow tests that run many different modules on a small set of sample data. Since the CI job for PRs is already set to use `make docker-maximum`, one could use any processor(s) after that. And we already have enough data in `core/repo/assets/` and workflows in `workflow-configuration/`. So the test would run that workflow on (say) `data/kant_aufklaerung_1784`, check it did not crash, check the target file group exists for all pages, and perhaps validate the workspace.

(We don't include any models in the standard distribution though. So one would either have to use a very simple workflow, or need an extra [step](https://github.com/OCR-D/ocrd_all/issues/65#issue-568617044) to install segmentation and recognition models.)

**Comment by stweil** [comment]
Some questions:

- When should such a CI test be triggered? Only for releases?
- Should it use a Docker container or use a separate build?
- On which platform should it run? Circle CI? Travis CI? GitHub Actions?

**Comment by bertsky** [comment]
>     * When should such a CI test be triggered? Only for releases?

As outlined above: for every new commit on a PR branch (via CircleCI rule `build`).

>     * Should it use a Docker container or use a separate build?

Good question. I have a feeling they are almost always the same, but you never know. So let's do the "harder" test, running all the above within a `docker run ocrd/all:maximum` (with appropriate mount points etc).

>     * On which platform should it run? Circle CI? Travis CI? GitHub Actions?

I am still with CircleCI, as everything has been set up already, and one could easily add more platforms there in the future.

**Comment by stweil** [comment]
> I am still with CircleCI

Personally I don't have access to the CircleCI results. I started several times to look for an account and always decided against it because I did not like to give them the required rights.

**Comment by M3ssman** [comment]
As this is designed as an OCR-D-Container-Systemtest, the workflow should focus on module integration, especially with known incompatibilities and, as to provide some sort of regression testing, on previously solved problems.

**Comment by bertsky** [comment]
> As this is designed as an OCR-D-Container-Systemtest, the workflow should focus on module integration, especially with known incompatibilities and, as to provide some sort of regression testing, on previously solved problems.

We probably could do more in this regard, but #362 contains a first-order approximation (`make test-workflow`).
