### ISSUE TITLE
avoid race for git lockfile when syncing modules in parallel

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd_all#123]
There's a race condition for the `.git/config.lock` file between parallel jobs when they want to synchronize / update some submodules. It must have been around for some time already, and only surfaces when using `make -j N` (i.e. with some fixed number of jobs), but not `make -j` (i.e. relative to the current system load-level).

_Originally posted by @bertsky in https://github.com/OCR-D/ocrd_all/pull/121_

**Comment by bertsky** [comment]
It's again unfortunate that all which GNU make offers here is global breakdown of concurrency via `.NOTPARALLEL`, where we instead want only local serialization.

For a synchronization mechanism with blocking behaviour on the shell, I can only think of using GNU parallel (which we already install under `deps-ubuntu` when `workflow-configuration` is not disabled). This would allow for example:
```make
$(OCRD_MODULES): always-update
	sem --id ocrd_all_git git submodule sync $(GIT_RECURSIVE) $@
	if git submodule status $(GIT_RECURSIVE) $@ | grep -qv '^ '; then \
		sem --id ocrd_all_git git submodule update --init $(GIT_RECURSIVE) $@ && \
		touch $@; fi
```

@stweil @kba opinions?

**Comment by stweil** [comment]
IMO pull request #124 is a simply and sufficient solution for this issue.

**Comment by bertsky** [comment]
> IMO pull request #124 is a simply and sufficient solution for this issue.

#124 would sacrifice the independence of builds for different modules, using `modules` as a single dependency for all executables, and would require downloading all modules even when (re-)installing only a single executable.

The `sem` solution is simple, too. It's also just a tiny change.

I would have started a PR for it already, but I still have difficulty reliably reproducing the above problem. The race seems to be more related to CPU load than network load. I want to be sure to understand the actual cause before rushing to conclusions.
