### ISSUE TITLE
Builds fail with "E: Unable to locate package tesseract-ocr-equ"

### ISSUE THREAD

**Issue by kba** [OCR-D/ocrd_all#133]
e.g. https://app.circleci.com/pipelines/github/OCR-D/ocrd_all/255/workflows/95b82aef-a41e-4741-a00b-a603cb62e4d9/jobs/254

Trying to reproduce locally. If anybody spots the problem, I'd appreciate any hints.

**Comment by kba** [comment]
https://app.circleci.com/pipelines/github/OCR-D/ocrd_all/260/workflows/9de9130e-e6ed-40cc-b9bb-fcc56671d58e/jobs/258 :'(

**Comment by bertsky** [comment]
There was a discussion on whether to include the equation recognition model from Tesseract 3 in the tessdata repos [here](https://github.com/tesseract-ocr/tessdata_fast/issues/4), which seems to have implications on whether or not they are bundled in Debian/Ubuntu automatically.

@stweil do you have any idea why this package suddenly disappeared from Ubuntu 18.04 bionic?

Also, it seems like [Alex's PPA](https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr?field.series_filter=bionic) renamed the packages from `tesseract-ocr` to `tesseract` and thus now has `tesseract-equ`...

**Comment by cneud** [comment]
> tesseract-ocr/tessdata_fast#4 gives more insight.
>
> For ocrd_all, I suggest to simply drop that package.

+1

**Comment by stweil** [comment]
@cneud, the package was already dropped in commit 85c7a97d. @kba, can we finally close this issue?
