### ISSUE TITLE
sub-venv logic ineffective when main venv was already active

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd_all#144]
When the user already has a virtual environment set up for herself and activated, ocrd_all picks it up (does not create a new one). But under this circumstance, creating sub-venvs does not work as expected: `python -m venv DIR` does **not** create new `pip` / `pip3` entry points then, which causes subsequent `pip` calls to use the main venv again.

This does _not_ happen when using `virtualenv` proper to create the sub-venv – which makes me wonder why we moved back from `python3-virtualenv` to `python3-venv` in the first place. From `virtualenv`'s [manual](https://virtualenv.pypa.io/en/latest/):
> The `venv` module does not offer all features of this library, to name just a few more prominent:
> ...
> - is not upgrade-able via `pip`,

This does also _not_ happen when the main venv gets deactivated before the sub-venv is created, even with the `venv` module.

So which of these 2 options is preferable as a fix?

**Comment by stweil** [comment]
Option 2 is the right one. See example [here](https://github.com/stweil/ocrd_all/blob/tf1/Makefile#L125).

**Comment by stweil** [comment]
> This does not happen when using virtualenv proper to create the sub-venv – which makes me wonder why we moved back from python3-virtualenv to python3-venv in the first place.

The answer is here: https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/.

**Comment by bertsky** [comment]
Thanks @stweil. I'll use the `deactivate` approach then.

**Comment by stweil** [comment]
> But under this circumstance, creating sub-venvs does not work as expected: python -m venv DIR does not create new pip / pip3 entry points then, which causes subsequent pip calls to use the main venv again.

I tried to reproduce this issue on Ubuntu, but everything works for me as expected. How can I reproduce the problem?

My test sequence was this:

    python3 -m venv venv
    source venv/bin/activate
    python3 -m venv venv/local
    source venv/local/bin/activate
    pip install wheel

**Comment by bertsky** [comment]
> I tried to reproduce this issue on Ubuntu, but everything works for me as expected. How can I reproduce the problem?
> 
> My test sequence was this:
> 
> ```
> python3 -m venv venv
> source venv/bin/activate
> python3 -m venv venv/local
> source venv/local/bin/activate
> pip install wheel
> ```

Damn. Cannot reproduce myself anymore :frowning:

**Comment by stweil** [comment]
So can we close this issue?

**Comment by bertsky** [comment]
Yes, let's close!
