### ISSUE TITLE
Tesseract must not be built with disable-shared

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd_all#15]
@stweil, what reason did you have for `--disable-shared` in https://github.com/UB-Mannheim/ocrd_all/blob/7d2306f94a1054bd051b46cc8c864fd9fec53f88/Makefile#L334?

This breaks both tesserocr install and scribo (which also links to -ltesseract) for me when no other Tesseract (from PPA) gets installed.

**Comment by stweil** [comment]
It works on a fresh Ubuntu installation. Maybe you are using cached files which still require the shared library.

**Comment by stweil** [comment]
One advantage is that it does not interfere with another Tesseract installation, so there is no danger of getting the wrong shared library.

Another advantage is faster code and smaller memory footprint.

**Comment by bertsky** [comment]
> It works on a fresh Ubuntu installation. Maybe you are using cached files which still require the shared library.

It does not work in the Docker build when no libtesseract.so is installed via PPA. 

The failure of `pip install tesserocr` I observed was due to another experiment (which used `-fsanitize=address` in Tesseract build). But scribo build fails like this:

```
make[6]: Entering directory '/build/ocrd_olena/olena-git/build/scribo/src/text'
  CXX      cleantxt.o
  CXXLD    cleantxt
  CXX      pbm_lines_recognition-pbm_lines_recognition.o
  CXXLD    pbm_lines_recognition
//usr/local/lib/libtesseract.a(libtesseract_api_la-baseapi.o): In function `tesseract::TessBaseAPI::Threshold(Pix**)':
/build/tesseract/build/src/api/../../../src/api/baseapi.cpp:2012: undefined reference to `pixDestroy'
```

So the `-ltesseract` is static now, and this necessitates enumerating all of its dependencies in the linker command for 3rd party components (like `-llept` in this case). (And tesserocr is special here, because its setup.py build rules already encapsulate that knowledge.)

**Comment by bertsky** [comment]
So maybe this _is_ an error on the part of Tesseract, in that it fails to properly set the libs for pkg-config when installing with `--disable-shared`?

**Comment by stweil** [comment]
Yes, `pkg-config` fails to give the right linker flags.

**Comment by bertsky** [comment]
Ok, then I guess Tesseract's `tesseract.pc.in` is the culprit. It says:
```
Libs: -L${libdir} -ltesseract @libarchive_LIBS@ @libcurl_LIBS@ @TENSORFLOW_LIBS@
Libs.private: -lpthread @OPENCL_LDFLAGS@
```

So `-llept` is missing in `Libs.private`? Do you want me to re-open (and re-name) https://github.com/tesseract-ocr/tesseract/issues/2803?

**Comment by bertsky** [comment]
And as a workaround here, maybe it's enough to add (`--enable-static` to configure and `--static` to pkg-config):
```make
	cd tesseract/build && ../configure --disable-openmp --disable-shared --enable-static --prefix="$(VIRTUAL_ENV)" CXXFLAGS="-g -O2 -fPIC"
	cd tesseract/build && $(MAKE) install PKG_CONFIG = 'pkg-config --static'
```

**Comment by stweil** [comment]
I think `--enable-static` is default, so that should not change anything. And `pkg-config --static --libs tesseract` currently does not return the right libraries for me.

**Comment by bertsky** [comment]
> I think `--enable-static` is default, so that should not change anything. And `pkg-config --static --libs tesseract` currently does not return the right libraries for me.

Oh, too bad! Back at the manual...

**Comment by bertsky** [comment]
> And `pkg-config --static --libs tesseract` currently does not return the right libraries for me.

I don't understand. This __does__ work for me:
```sh
pkg-config --libs --static tesseract.pc
-L/usr/local/lib -ltesseract -lpthread -llept -lz -lpng -ljpeg -lgif -ltiff -lwebp
```

(And yes, I do get the same result for the `tesseract.pc` installed via non-static builds, i.e. when running `pkg-config --libs --static tesseract` after `sudo make install`. And yes, it does not depend on the order of the arguments to pkg-config.)

So the question is _not_ why the private libs don't appear in `Libs.private`, but why the generated makefiles don't call `pkg-config` with `--static`.

I found a [manual](https://autotools.io/pkgconfig/dependencies.html#pkgconfig.static-link) which recommends `./configure LDFLAGS="-static" PKG_CONFIG="pkg-config --static"` instead of `./configure --disable-shared`.

This at least shows we also need `libgif-dev` (for the static version of libgif) now, but the problem of not finding -llept at olena build time still remains.

**Comment by bertsky** [comment]
@stweil, Look, this already consumes way to much time. Couldn't we just drop the static build for now, and come back when this is configured correctly either in Tesseract itself or we have a workaround for the call to `configure`? This is holding up development of more important features than a little performance gain.

**Comment by stweil** [comment]
> It does not work in the Docker build when no libtesseract.so is installed via PPA.

I'll have a look. A similar scenario is building on a new machine, and that definitely works for me.

@bertsky, @kba, I also like simple solutions, but just dropping the static build is no solution at all. Let me try to break thinks down:

- In controlled environments (Docker container, chroot) both static and non static builds should work with any version of Tesseract. We could use non static builds there. Or we fix the problem with static builds, get faster compilation, reduce the Docker image size and get a slight performance gain.
- In complex environments (Linux computer with potentially several installations of Tesseract), non static builds are fine for stable Tesseract versions like 4.1 from PPA.
- Using non static builds with latest Tesseract will result in complex problems, for example crashing applications or misfunction. Version 5 is currently still a moving target with changing API. For example a class can change the order of its member variables or its size at any time, causing crashes or strange effects. Signatures of functions can change, resulting in unresolved symbols at runtime.

**Comment by bertsky** [comment]
Yes, these are very good reasons. (Maybe we should document that in the Makefile's comments, or even the README.)

I should revert 2dfe06a of #24. But it needs to be replaced by a working solution for ocrd_olena build (at least in Docker).

So how do we progress this: try to find a fix in Tesseract (in how we configure autoconf/pkg-config), or a better workaround here (in how we call autoconf/pkg-config)? I could also try patching ocrd_olena to ignore Tesseract (e.g. `--with-tesseract=no` might work)...

**Comment by bertsky** [comment]
(BTW, as you can see [here](https://github.com/OCR-D/ocrd_all/blob/009a042a65e79ee4f90788bc31c8235602fdb844/Makefile#L375), we also actually need more dev packages with static build. So it's no simple revert anyway.)

**Comment by bertsky** [comment]
> I should revert [2dfe06a](https://github.com/OCR-D/ocrd_all/commit/2dfe06a0a37557eaca87b36888b16eb7674ab901) of #24. But it needs to be replaced by a working solution for ocrd_olena build (at least in Docker).
> 
> So how do we progress this: try to find a fix in Tesseract (in how we configure autoconf/pkg-config), or a better workaround here (in how we call autoconf/pkg-config)? I could also try patching ocrd_olena to ignore Tesseract (e.g. `--with-tesseract=no` might work)...
> 
> (BTW, as you can see [here](https://github.com/OCR-D/ocrd_all/blob/009a042a65e79ee4f90788bc31c8235602fdb844/Makefile#L375), we also actually need more dev packages with static build. So it's no simple revert anyway.)

This does work – see OCR-D/ocrd_olena#18 and https://github.com/OCR-D/ocrd_all/pull/24/commits/b6acabb92715120774c0c31af432e48053bd64cd.
