### ISSUE TITLE
Builds with missing TF create unusable "executables"

### ISSUE THREAD

**Issue by stweil** [OCR-D/ocrd_all#152]
`make all` with Python 3.8 fails because of missing TF modules.

    ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.15.* (from ocrd-cor-asv-ann==0.1.2) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
    ERROR: No matching distribution found for tensorflow-gpu==1.15.* (from ocrd-cor-asv-ann==0.1.2)
    make[1]: *** [Makefile:213: /home/stweil/src/github/OCR-D/venv-20200813/local/sub-venv/headless-tf1/bin/ocrd-cor-asv-ann-evaluate] Fehler 1
    make[1]: Verzeichnis „/home/stweil/src/github/OCR-D/ocrd_all“ wird verlassen
    make: *** [Makefile:209: /home/stweil/src/github/OCR-D/venv-20200813/bin/ocrd-cor-asv-ann-evaluate] Fehler 2
    (venv-20200813) stweil@bss11:~/src/github/OCR-D/ocrd_all$ ls -l $VIRTUAL_ENV/bin/ocrd-cor*
    -rw-r--r-- 1 stweil stweil   209 Aug 17 19:59 /home/stweil/src/github/OCR-D/venv-20200813/bin/ocrd-cor-asv-ann-evaluate
    -rw-r--r-- 1 stweil stweil   208 Aug 17 19:59 /home/stweil/src/github/OCR-D/venv-20200813/bin/ocrd-cor-asv-ann-process

Repeating `make all` sufficiently often (or running `make all -k` "builds" all processors, and make claims that there remains nothing to do although it only created non-executable stubs in `venv/bin`.

Related issues: #147, #150.

**Comment by bertsky** [comment]
@stweil can you please repeat under #145 (which includes `.DELETE_ON_ERROR`) to verify this solves it?

**Comment by stweil** [comment]
@bertsky, I merged now commit ca242633a41730d7ce9c2a8f1c8206c94049e55b which solves this issue.
