### ISSUE TITLE
Building tesserocr fails in parallel builds

### ISSUE THREAD

**Issue by stweil** [OCR-D/ocrd_all#160]
tesserocr depends on an installed tesseract. This dependency is currently missing in the `Makefile`. A fresh parallel build tries to build tesserocr before the tesseract build is finished and fails therefore:

    tesserocr.cpp:658:10: fatal error: tesseract/publictypes.h: No such file or directory

**Comment by stweil** [comment]
There might be another problem: nearly all processors depend on the Python package `ocrd`. So their build should wait until that package was built. I expect that there exist more dependencies which have to be fixed for parallel builds.

**Comment by bertsky** [comment]
> tesserocr depends on an installed tesseract. This dependency is currently missing in the `Makefile`. A fresh parallel build tries to build tesserocr before the tesseract build is finished and fails therefore:
> 
> ```
> tesserocr.cpp:658:10: fatal error: tesseract/publictypes.h: No such file or directory
> ```

That's as easy as adding
```make
$(SHARE)/tesserocr: $(BIN)/tesseract
```

**Comment by bertsky** [comment]
> There might be another problem: nearly all processors depend on the Python package `ocrd`. So their build should wait until that package was built. I expect that there exist more dependencies which have to be fixed for parallel builds.

I don't think that's an actual problem. The `ocrd` dependency is usually resolved via `pip`. Our core module's version might get overruled by that (or not), but there's always going to be _some_ version.

**Comment by stweil** [comment]
> That's as easy as adding ...

Yes, nearly. See PR #164.

**Comment by stweil** [comment]
Fixed with PR #164, so closing it.
