### ISSUE TITLE
Build on macOS fails to create delegator scripts for executables in sub-venvs

### ISSUE THREAD

**Issue by stweil** [OCR-D/ocrd_all#192]
It tries to run the `chmod`:

    chmod: /Users/stweil/src/github/OCR-D/venv-20200917/bin/ocrd-segment-evaluate: No such file or directory
    [...]

**Comment by bertsky** [comment]
Please give us the log output of what happened before.

**Comment by stweil** [comment]
I am afraid that log output won't help much, nevertheless here it is:

    Successfully installed ocrd-segment-0.1.1
    make[1]: Nothing to be done for `ocrd-segment-from-masks'.
    make[1]: Nothing to be done for `ocrd-segment-from-coco'.
    make[1]: Nothing to be done for `ocrd-segment-extract-lines'.
    make[1]: Nothing to be done for `ocrd-segment-extract-regions'.
    make[1]: Nothing to be done for `ocrd-segment-extract-pages'.
    make[1]: Nothing to be done for `ocrd-segment-replace-original'.
    make[1]: Nothing to be done for `ocrd-segment-repair'.
    chmod +x /Users/stweil/src/github/OCR-D/venv-20200917/bin/ocrd-segment-evaluate /Users/stweil/src/github/OCR-D/venv-20200917/bin/ocrd-segment-from-masks /Users/stweil/src/github/OCR-D/venv-20200917/bin/ocrd-segment-from-coco /Users/stweil/src/github/OCR-D/venv-20200917/bin/ocrd-segment-extract-lines /Users/stweil/src/github/OCR-D/venv-20200917/bin/ocrd-segment-extract-regions /Users/stweil/src/github/OCR-D/venv-20200917/bin/ocrd-segment-extract-pages /Users/stweil/src/github/OCR-D/venv-20200917/bin/ocrd-segment-replace-original /Users/stweil/src/github/OCR-D/venv-20200917/bin/ocrd-segment-repair
    chmod: /Users/stweil/src/github/OCR-D/venv-20200917/bin/ocrd-segment-evaluate: No such file or directory
    chmod: /Users/stweil/src/github/OCR-D/venv-20200917/bin/ocrd-segment-from-masks: No such file or directory
    chmod: /Users/stweil/src/github/OCR-D/venv-20200917/bin/ocrd-segment-from-coco: No such file or directory
    chmod: /Users/stweil/src/github/OCR-D/venv-20200917/bin/ocrd-segment-extract-lines: No such file or directory
    chmod: /Users/stweil/src/github/OCR-D/venv-20200917/bin/ocrd-segment-extract-regions: No such file or directory
    chmod: /Users/stweil/src/github/OCR-D/venv-20200917/bin/ocrd-segment-extract-pages: No such file or directory
    chmod: /Users/stweil/src/github/OCR-D/venv-20200917/bin/ocrd-segment-replace-original: No such file or directory
    chmod: /Users/stweil/src/github/OCR-D/venv-20200917/bin/ocrd-segment-repair: No such file or directory
    make: *** [/Users/stweil/src/github/OCR-D/venv-20200917/bin/ocrd-segment-evaluate] Error 1

**Comment by stweil** [comment]
Note that macOS comes with GNU Make 3.81 which is really old. Maybe a short demo Makefile can be used to examine this issue and to see whether there is any chance to get the delegators working.

**Comment by bertsky** [comment]
Oh, I see. No more debugging necessary – our makefile needs the `file` function introduced in 4.0. I guess we should check `MAKE_VERSION` for such constructs...
