### ISSUE TITLE
Build and install core from code in the local venvs

### ISSUE THREAD

**Issue by kba** [OCR-D/ocrd_all#195]
With the local-venv-mechanism, core is installed once in the "root" venv and once in each venv.

When doing `make all` after an update, only the root core installation is updated IIUC.

So in addition to [moving core to the front of the list of modules to install](https://github.com/OCR-D/ocrd_all/pull/187#issuecomment-688944306) we should make sure, that core is updated consistently across venvs.

**Comment by bertsky** [comment]
> So in addition to [moving core to the front of the list of modules to install](https://github.com/OCR-D/ocrd_all/pull/187#issuecomment-688944306) we should make sure, that core is updated consistently across venvs.

The latter is entailed by the former BTW. (Once we make the dependency on core explicit, it will trigger recursively too.)

**Comment by kba** [comment]
Workaround until this is fixed:

```
git pull
make all
# next steps not necessary once #195 is fixed
(source venv/local/sub-venv/headless-tf1/; cd core; make install)
(source venv/local/sub-venv/headless-tf22/; cd core; make install)
```

**Comment by VolkerHartmann** [comment]
I did this:
git pull
make all
source venv/local/sub-venv/headless-tf1/bin/activate; cd core; make install
deactivate
cd ..
source venv/local/sub-venv/headless-tf22/bin/activate; cd core; make install
deactivate
cd ..
 . venv/bin/activate
-->
ocrd-segment-repair --version
Version 0.1.2, ocrd/core 2.16.3

**Comment by bertsky** [comment]
> Workaround until this is fixed:
> 
> ```
> git pull
> make all
> # next steps not necessary once #195 is fixed
> (source venv/local/sub-venv/headless-tf1/; cd core; make install)
> (source venv/local/sub-venv/headless-tf22/; cd core; make install)
> ```

More generally, I think it is "enough" to force updating all modules:

    git submodule foreach 'touch $path'
    make all

**Comment by stweil** [comment]
> More generally, I think it is "enough" to force updating all modules

No, that does not update core in sub venvs for me.

**Comment by kba** [comment]
> No, that does not update core in sub venvs for me

You mean the workaround does not work for you? Why, it does for me?

**Comment by stweil** [comment]
@kba workaround: works
@bertsky workaround: creates new empty files, does not work

**Comment by bertsky** [comment]
> No, that does not update core in sub venvs for me. Using `git submodule foreach 'touch .'` also does not help.

Sorry – I should have said: `touch -c`

**Comment by stweil** [comment]
A closer look on this issues shows that `core` is currently never build in the sub venvs. It is only installed from PyPI as a required Python module. So the fix should not be difficult: add the missing make statements for core.

**Comment by stweil** [comment]
See pull request #202 for a working fix.

**Comment by stweil** [comment]
I updated the title of this issue to better reflect the problem which is not updating core from PyPI but building core at all for the sub venvs.
