### ISSUE TITLE
Drop ocrd_ocropy ?

### ISSUE THREAD

**Issue by cneud** [OCR-D/ocrd_all#21]
All functionality from ``ocrd_ocropy`` is now supported/superseded by [ocrd_cis](https://github.com/cisocrgroup/ocrd_cis).

**Comment by bertsky** [comment]
Yes. It's similar to the ocrd_kraken issue (#11): we will get back to this in the future, but should remove it soon.

**Comment by bertsky** [comment]
How about deactivating this via the same [mechanism](https://github.com/OCR-D/ocrd_all/blob/bcbf7b99d2f7fa690dfe863e5237f7a1d7178d54/Makefile#L42) like `cor-asv-fst`?

**Comment by cneud** [comment]
> How about deactivating this via the same [mechanism](https://github.com/OCR-D/ocrd_all/blob/bcbf7b99d2f7fa690dfe863e5237f7a1d7178d54/Makefile#L42) like `cor-asv-fst`?

TBH I see no point in merely *deactivating* over *removing* ``ocrd_ocropy`` when

a) all functionality from ``ocrd_ocropy`` is now supported/superseded by [ocrd_cis](https://github.com/cisocrgroup/ocrd_cis)
b) no one is ready and willing to update/maintain ``ocrd_ocropy`` in the future

**Comment by bertsky** [comment]
> no one is ready and willing to update/maintain `ocrd_ocropy` in the future

That's not true: We are still planning on reworking my `ocrd_cis` changes into a subset `ocropy` (targeted for upstream approval by tmbdev) and another `ocrd_ocropy` (for the OCR-D wrappers only).

**Comment by kba** [comment]
>> no one is ready and willing to update/maintain `ocrd_ocropy` in the future

> We are still planning on reworking

That will be a rewrite, at least the ocrd_ocropy part. I do still have it on the agenda to get your improvements upstream but a lot of things are higher priority at the moment. Unfortunately, I've used both ocrd_kraken and ocrd_ocropy copiously in slides and documentation so users tend to try out these two projects. Even I tend to get confused about unexpected behavior and ouput of `ocrd-ocropy-regognize` until I realize I'm missing the `-cis-` in the command.

Removing the projects from ocrd_all does not mean that we abandon the projects (I very much intend to revive the kraken wrapper at some point), just that we restrict ocrd_all to contain only projects that are functioning properly.

**Comment by bertsky** [comment]
I understand, but with the same argument you could see how if users find `ocrd_kraken` and `ocrd_ocropy` missing here they might consider this as an error.

Merely disabling these modules also ensures users won't be able to use / confuse them (both with local and Docker builds).

Plus keeping the build configuration makes it easier to reintegrate later (because general changes to rules/concepts can be dragged along).

But I don't feel strongly about it, so please go ahead.
