### ISSUE TITLE
TypeError in ocrd-cis-ocropy-segment

### ISSUE THREAD

**Issue by b2m** [OCR-D/ocrd_all#221]
In the newest [v2018-11-18](https://github.com/OCR-D/ocrd_all/releases/tag/v2018-11-18) [sic] a `TypeError` is thrown when using `ocrd-cis-ocropy-segment`.

```bash
Traceback (most recent call last):
  File "/usr/bin/ocrd-cis-ocropy-segment", line 33, in <module>
    sys.exit(load_entry_point('ocrd-cis', 'console_scripts', 'ocrd-cis-ocropy-segment')())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/build/ocrd_cis/ocrd_cis/ocropy/cli.py", line 53, in ocrd_cis_ocropy_segment
    return ocrd_cli_wrap_processor(OcropySegment, *args, **kwargs)
  File "/build/core/ocrd/ocrd/decorators/__init__.py", line 81, in ocrd_cli_wrap_processor
    run_processor(processorClass, ocrd_tool, mets, workspace=workspace, **kwargs)
  File "/build/core/ocrd/ocrd/processor/helpers.py", line 69, in run_processor
    processor.process()
  File "/build/ocrd_cis/ocrd_cis/ocropy/segment.py", line 289, in process
    input_file.pageId, zoom, rogroup=rogroup)
  File "/build/ocrd_cis/ocrd_cis/ocropy/segment.py", line 619, in _process_element
    file_grp=self.output_file_grp)
TypeError: save_image_file() got an unexpected keyword argument 'pageId'
```

The reason is, that somehow a commit not in the `ocrd_cis` main repository from a branch by @bertsky was introduced (https://github.com/bertsky/ocrd_cis/commit/4b46ea97806945c0773fa642ff2bbe54ef4dd506) in `ocrd_all`. This commit has a typo when calling `save_image_file()`: `pageId` instead of `page_id`.

**Comment by kba** [comment]
Thanks for the detailled report. `ocrd_cis` in ocrd_all is currently not at master but at https://github.com/cisocrgroup/ocrd_cis/pull/77 (on @bersky's request).

**Comment by bertsky** [comment]
Thanks @b2m, I know, this has been fixed later-on in the same PR (in 3858fe7c73bc87f0ddddee684974553d5b9a2835). Sorry for the inconvenience.

**Comment by b2m** [comment]
Thanks for the commit reference... momentarily grateful for `git` in the docker images 😄 .

**Comment by b2m** [comment]
As a new version of `ocrd_all` was released this issue can be resolved through updating to the latest version.

**Comment by bertsky** [comment]
Not merged yet!

**Comment by b2m** [comment]
The mentioned pull request for crd_cis is not merged yet.

The problem in `ocrd_all` is no longer reproducible as the "fix" from mentioned pull request was also pulled into `ocrd_all` and released last week.

But if it is somehow important to keep this bug report open until the pull request is merged, then let's keep it open ;)

**Comment by kba** [comment]
I only now realize  from the `[sic]` in your initial post that I released an [ocrd_all version off by two years](https://github.com/OCR-D/ocrd_all/releases/tag/v2018-11-18). The dockerhub tag is correct though. Funny how I did not notice this at all...

Let's keep this open as a reminder to keep ocrd_cis submodule in ocrd_all at https://github.com/cisocrgroup/ocrd_cis/pull/77 until that is merged.

**Comment by stweil** [comment]
@kba, I think it would not harm (but help) if we replaced that tag by one with the correct year. Should I do that?

**Comment by kba** [comment]
Was gonna do this when finishing the next release, but thanks, yes please.
