### ISSUE TITLE
VIRTUAL_ENV parameter not working correctly

### ISSUE THREAD

**Issue by andbue** [OCR-D/ocrd_all#228]
Hi, when installing ocrd for the first time I tried to follow the instructions in README.md. The following line
`make [PYTHON=python3] [VIRTUAL_ENV=./venv] [OCRD_MODULES="..."] [TARGET...]`
made me think that the parameter VIRTUAL_ENV was needed to specify the directory for the installation. It seems (at least that's what @kba told me) that the parameter is not really helpful when calling "make all", as it is passed to every single package, leading to conflicts between package versions. Maybe the readme could be more explicit in the description of the variables.

Interestingly enough, the installation somehow finished and was mostly working. The modules ocrd-sbb-binarize and ocrd-sbb-textline-detector needed fixed imports like
```python
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```
to run with the newer tensorflow and the GPU was not used by default (did not investigate further). Maybe it would be a good idea to upgrade the sbb- modules to tf2 to let users profit from improvements in performance, but that would call for some testing, I guess.

**Comment by cneud** [comment]
> Maybe it would be a good idea to upgrade the sbb- modules to tf2

Just a quick comment on this - yes this would be nice, but also a lot of work. There are not only API breaking changes that need to be manually checked and adapted in the sources, but also models would have to be re-trained (and accordingly, performance with TF1 versions evaluated). I am not convinced we can and will pull this off during the remaining running time of the Qurator project (where the sbb_* tools are developed).

**Comment by bertsky** [comment]
Not sure this is a documentation issue or a behavioural one. The square brackets universally denote optional information in shell call mnemonics. But what you report (ie. sub-venvs conflated into a single venv) should not happen.

I have no time to investigate now, but could you please post the contents of `$VIRTUAL_ENV/bin/ocrd-sbb-binarize`?

**Comment by kba** [comment]
> It seems (at least that's what @kba told me) that the parameter is not really helpful when calling "make all", as it is passed to every single package, leading to conflicts between package versions. 

I have never tried passing `VIRTUAL_ENV` to the make call, we assume that if you have a preexisting venv you want to install into, you'd just have it activated when doing `make all`. But it shouldn't make a difference. This still doesn't explain how the recursive `make` calls would reuse the top-level `VIRTUAL_ENV` since we explicitly override them (e.g. `$(OCRD_CALAMARI): VIRTUAL_ENV := $(SUB_VENV)/headless-tf2`).

Can you post the output of 

```sh
ls -la $VIRTUAL_ENV/local/sub-venv
```

and

```sh
cat $VIRTUAL_ENV/bin/ocrd-calamari-recognize
```

(The latter *SHOULD* be just a small bash wrapper that delegates to the correct venv)

**Comment by stweil** [comment]
@andbue, which value did you pass for `VIRTUAL_ENV`? It is expected to be an absolute path.

**Comment by andbue** [comment]
The command was `make VIRTUAL_ENV=~/ocrd_venv all`. Maybe it was a bit mixed up because I started `make` a second time without deleting the venv after realizing that I still needed some dependencies. Inside the venv there is no "./local" directory. The shebangs of the scripts in `$VIRTUAL_ENV/bin/` also point to the python  `$VIRTUAL_ENV/bin/python3`, e.g. in ocrd-calamari-recognize:
```python
#!/home/[my user]/ocrd_venv/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from ocrd_calamari.cli import ocrd_calamari_recognize
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(ocrd_calamari_recognize())
```
I realized from the readme that VIRTUAL_ENV was meant to be an optional parameter but passed it anyway, maybe to have some control over where this ominous makefile I just downloaded would write several GB of data to ;-). If the makefile normally creates sub-venvs, the readme is just fine as it is. Somehow I seem to have managed to override that feature.

**Comment by stweil** [comment]
I can reproduce the problem. Pull request #229 should fix it.

**Comment by stweil** [comment]
This issue is fixed now.
