### ISSUE TITLE
How to dewarp deskewed image (on page level) using ocrd-anybaseocr-dewarp

### ISSUE THREAD

**Issue by Aysoltan** [OCR-D/ocrd_all#246]
ocrd-anybaseocr-dewarp with the command:

`ocrd-anybaseocr-dewarp -I OCR-D-DESKEW-PAGE -O OCR-D-DEWARP-PAGE -p '{\"pix2pixHD\":\"../ocr_all/pix2pixHD/\",\"latest_net_G.pth\":\"../ocr_all/pix2pixHD/models\"}'`

resolves the following error:
`ValueError: Error parsing '{\"pix2pixHD\":\"../ocr_all/pix2pixHD/\",\"latest_net_G.pth\":\"../ocr_all/pix2pixHD/models\"}': Expecting property name enclosed in double quotes: line 1 column 2 (char 1)`

Any idea how to use ocrd-anybaseocr-dewarp properly?

**Comment by kba** [comment]
This is an issue witht he JSON syntax. There is a simpler variant of the `-p` parameter: `-P` (capital P). This allows you to specify individual parameter key-value pairs without the JSON syntax:

```
ocrd-anybaseocr-dewarp -I OCR-D-DESKEW-PAGE -O OCR-D-DEWARP-PAGE -P model_path /path/to/latest_net_G.pth'
```

But I would recommend that you download the model with `ocrd resmgr` which takes care of placing the model in the right location, so you don't have to specify the model at all:

```sh
ocrd resmgr download ocrd-anybaseocr-dewarp '*'
# once that is finished, no need for an explicit parameter model_path because the default should work now
ocrd-anybaseocr-dewarp -I OCR-D-DESKEW-PAGE -O OCR-D-DEWARP-PAGE
```

Where did you get the parameters from? They are outdated, if we have this in our documentation still, I would like to update that.

**Comment by Aysoltan** [comment]
The parameters are from: [(https://ocr-d.de/en/workflows)] (look at Step 6: Dewarping (Page Level))

So I downloaded the model ocrd resmgr with `ocrd resmgr download ocrd-anybaseocr-dewarp '*'` so far.
After runing `ocrd-anybaseocr-dewarp -I OCR-D-DESKEW-PAGE -O OCR-D-DEWARP-PAGE`

the following error message is returned: 
` input_label = label_map.data.cuda()
  File "/home/superman/ocrd_all/venv/local/sub-venv/headless-tf21/lib/python3.6/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx`

**Comment by kba** [comment]
> The parameters are from: [https://ocr-d.de/en/workflows] (look there at Step 6: Dewarping (Page Level))

Indeed, that is outdated, thanks for the heads-up, I'll fix it.

The dewarping does require a GPU and working CUDA setup. Do you have an NVIDIA graphic card in your machine? If so, you might want to install the CUDA toolkit. While it is a hard requirement for this processor, it's a massive speed boost for many other processors.

If you don't have a GPU, have a look at `ocrd-cis-ocropy-dewarp` which does support dewarping on line-level.

**Comment by Aysoltan** [comment]
Thanks for the hint. We will try to intigrate the high-performance GPU like NVIDIA later.

Now another thing: performing
`ocrd-tesserocr-segment -I OCR-D-DESKEW-PAGE -O OCR-D-SEG -P find_tables false -P shrink_polygons true`

resolves the following error message:
```
File "/home/superman/ocrd_all/venv/lib/python3.6/site-packages/ocrd_tesserocr/recognize.py", line 217, in process
    model = get_languages()[1][-1] # last installed model
IndexError: list index out of range
```
?

**Comment by kba** [comment]
> Thanks for the hint. We will try to intigrate the high-performance GPU like NVIDIA later.
> 
> Now another thing: performing
> `ocrd-tesserocr-segment -I OCR-D-DESKEW-PAGE -O OCR-D-SEG -P find_tables false -P shrink_polygons true`
> 
> resolves the following error message:
> 
> ```
> File "/home/superman/ocrd_all/venv/lib/python3.6/site-packages/ocrd_tesserocr/recognize.py", line 217, in process
>     model = get_languages()[1][-1] # last installed model
> IndexError: list index out of range
> ```
> 
> ?

You need to have the `osd` and `eng` models installed as a minimum. Try

```
ocrd resmgr download ocrd-tesserocr-recognize '*'
```

which will install all the relevant models (don't worry, they are just a few MiB per model).

**Comment by kba** [comment]
BTW, you can call `make install-models` in the ocrd_all repo root folder to install all the models for all the processors in one go and not have to install them piece-by-piece later on.

**Comment by Aysoltan** [comment]
Many thanks for your hints. Everything went well. Is there also some commad for downloadind cor-asv-ann-models for post-correction?

**Comment by kba** [comment]
>  Is there also some commad for downloadind cor-asv-ann-models for post-correction?

No, I think they are only available via Git LFS which we haven't implemented an integration for. @bertsky?

**Comment by bertsky** [comment]
> Many thanks for your hints. Everything went well. Is there also some commad for downloadind cor-asv-ann-models for post-correction?

@Aysoltan 
No, we have not integrated these into the `ocrd resmgr` mechanism yet. You need to download them from the [Github webpage](https://github.com/ASVLeipzig/cor-asv-ann-models). Or better yet (because our LFS quota there is very small), from our [Gitlab webpage](https://git.informatik.uni-leipzig.de/ocr-d/cor-asv-ann-models), which it is a mirror of.

For more information on the models, please contact me via Gitter (same nick as here) or open an issue on https://github.com/ASVLeipzig/cor-asv-ann.
