### ISSUE TITLE
Unable to find a valid copy of libtoolize or glibtoolize in your PATH!

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_all#259]
On a rather pristine Debian host:

~~~
cd tesseract && ./autogen.sh
Unable to find a valid copy of libtoolize or glibtoolize in your PATH!
./autogen.sh: 59: ./autogen.sh: bail_out: not found
Running aclocal
./autogen.sh: 77: ./autogen.sh: aclocal: not found

  Something went wrong, bailing out!

make: *** [Makefile:698: tesseract/Makefile.in] Error 1
~~~

An `apt install build-essential libtool pkg-config` appears to fix the immediate problem. I wasn't sure where to put this in the README, so I decided to open this issue instead of doing a PR.

**Comment by stweil** [comment]
Yes, the dependencies listed in `Makefile` did not match those which are [required for Tesseract builds](https://tesseract-ocr.github.io/tessdoc/Compiling-%E2%80%93-GitInstallation.html).

Pull request #260 tries to fix that.

**Comment by stweil** [comment]
`build-essentials` are not required, but `libtool` and `pkg-config` are required.

**Comment by kba** [comment]
Fixed in https://github.com/OCR-D/ocrd_all/pull/260/files
