### ISSUE TITLE
default Tesseract installation segfaults because there is no tessdata

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd_all#268]
The current 93c517b9c9ad79c78e6dfa37a7d0048f6393fa11's CI failures are all segfaults during calls to `ocrd-tesserocr-* --help`.

I can reproduce this with `make check` using a vanilla native installation.

What's more: I can reproduce this by simply:

    python -c 'import tesserocr'

Further experiments show that this happens during exit. 

Apparently the problem is that in tesserocr.pyx there's a [module-level API initialization](https://github.com/sirfz/tesserocr/blob/711cbab544dbb4bd3dcf1f13aad9d0fef20fcac7/tesserocr.pyx#L56) with NULL arguments (i.e. on the [default path and model](https://github.com/tesseract-ocr/tesseract/blob/e176169a90a3fb19c2c27c41f7c2666b021cd2c7/include/tesseract/baseapi.h#L217-L219)), which [amounts](https://github.com/tesseract-ocr/tesseract/blob/e176169a90a3fb19c2c27c41f7c2666b021cd2c7/src/api/baseapi.cpp#L414) [to](https://github.com/tesseract-ocr/tesseract/blob/e176169a90a3fb19c2c27c41f7c2666b021cd2c7/src/ccmain/tessedit.cpp#L83) calling [CCUtil::main_setup](https://github.com/tesseract-ocr/tesseract/blob/e176169a90a3fb19c2c27c41f7c2666b021cd2c7/src/ccutil/mainblk.cpp#L44-L91) with an empty string for argv0 (the path parameter), which (unless an environment variable `TESSDATA_PREFIX` is available or a symbol `TESSDATA_PREFIX` has been compiled in) makes Tesseract try with `datadir = "./"`, and `lang = "eng"`. 

Naturally, this should result in an ["error opening datafile ./eng.traineddata"](https://github.com/tesseract-ocr/tesseract/blob/e176169a90a3fb19c2c27c41f7c2666b021cd2c7/src/ccmain/tessedit.cpp#L94) message on stderr – but  tesserocr [redirects](https://github.com/sirfz/tesserocr/blob/711cbab544dbb4bd3dcf1f13aad9d0fef20fcac7/tesserocr.pyx#L55) this to /dev/null, we don't see it. Also, tesserocr does not check the return status of `TessBaseAPI::Init` (which would be -1 under these circumstances).

Now, I believe the real problem is tesserocr's [calling](https://github.com/sirfz/tesserocr/blob/711cbab544dbb4bd3dcf1f13aad9d0fef20fcac7/tesserocr.pyx#L65) `TessBaseAPI::End` after this, which (among others) [delegates](https://github.com/tesseract-ocr/tesseract/blob/e176169a90a3fb19c2c27c41f7c2666b021cd2c7/src/api/baseapi.cpp#L2238) to `Tesseract::Clear`. And AFAICT that then ends up [adding](https://github.com/tesseract-ocr/tesseract/blob/e176169a90a3fb19c2c27c41f7c2666b021cd2c7/src/ccmain/tesseractclass.cpp#L449) a string (`"_debug.pdf"`) to a nullptr (`imagebasename`).

**Comment by bertsky** [comment]
Fixed by https://github.com/sirfz/tesserocr/pull/265 – maybe we should just update our tesserocr submodule to that branch as workaround.

**Comment by stweil** [comment]
No. The segfaults are caused by a bug in Tesseract code. See discussion for https://github.com/tesseract-ocr/tesseract/pull/3330.

**Comment by stweil** [comment]
I expect that ocrd_tesserocr* will also fail with a segmentation fault if you install tessdata.

**Comment by stweil** [comment]
PR #269 should fix the segmentation faults.

**Comment by stweil** [comment]
For those who are interested in details of the bug:

tesserocr uses a global `TessBaseAPI` object. This object creates a static singleton object under certain conditions, for example when `TessBaseAPI::End()` was called. Those two objects are destroyed when the program terminates. The crash occurs because the singleton object is destroyed before the `TessBaseAPI` object. When that object is destroyed, it runs `TessBaseAPI::End()` again and tries to use the destroyed singleton object.

**Comment by bertsky** [comment]
Thanks @stweil!
