### ISSUE TITLE
wanted: /usr/bin/time in docker image

### ISSUE THREAD

**Issue by jbarth-ubhd** [OCR-D/ocrd_all#271]

**Comment by stweil** [comment]
Are there any reasons against that suggestion? It will increase the storage need by 132 kb. That should not be a problem.

**Comment by kba** [comment]
No, including `time` is not an issue of course. Should we add it to the ocrd_all Dockerfile or to the core base image? The latter probably, to make it available for all derived images?

**Comment by stweil** [comment]
I agree that the latter looks like the better option.

**Comment by bertsky** [comment]
Yes, I'd argue the latter. (It would also give us the opportunity to implement `ocrd.process.profile` measurements from bashlib.)

**Comment by kba** [comment]
Fixed in https://github.com/OCR-D/core/pull/748
