### ISSUE TITLE
`make all` with Python 3.7 fails to build ocrd_detectron2

### ISSUE THREAD

**Issue by stweil** [OCR-D/ocrd_all#291]
The build aborts with this error message:
```
ERROR: Could not find a version that satisfies the requirement detectron2>=0.6 (from versions: none)
```

I could fix it locally in the main venv (no need to use `sub-venv/headless-torch14`) using these commands:

```
cd ocrd_detectron2
pip install 'git+https://github.com/facebookresearch/detectron2.git'
pip install -r requirements.txt
pip install .
```

Building `detectron2` instead of trying to get (non-existing) pre-built packages would also support more platforms which currently would also fail (non Linux hosts, non x86_64 architectures).

**Comment by bertsky** [comment]
> Building `detectron2` instead of trying to get (non-existing) pre-built packages would also support more platforms which currently would also fail (non Linux hosts, non x86_64 architectures).

That does not work in general though. (You have to accommodate Python, Pytorch and Detectron versions against each other. Even the official setup manual does not do it this way.) Plus it will take very long. (Plus we might not want to depend on unstable master.)
