### ISSUE TITLE
ocrd_all: make all creates error

### ISSUE THREAD

**Issue by stefanCCS** [OCR-D/ocrd_all#303]
Hi,
I have tried to update the current (23.02.2022) ocrd_all `using git pull` and `make clean` and` make all`.
Unfortunately, I get this error:
```
cd ocrd_anybaseocr ; make patch-pix2pixhd
make[2]: Entering directory '/home/ocrdadmin/ocrd_all/ocrd_anybaseocr'
git submodule update --init
From https://github.com/NVIDIA/pix2pixHD
 * branch            e524de235b251adddee6ca2bcbd31115a834077c -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by checkout:
        data/custom_dataset_data_loader.py
        data/data_loader.py
        models/base_model.py
        models/networks.py
        models/pix2pixHD_model.py
        options/base_options.py
Please commit your changes or stash them before you switch branches.
Aborting
Unable to checkout 'e524de235b251adddee6ca2bcbd31115a834077c' in submodule path 'ocrd_anybaseocr/pix2pixhd'
Makefile:72: recipe for target 'pix2pixhd' failed
```

**Comment by kba** [comment]
We should probably add a `clean` target to ocrd_anybaseocr and delegate to it on `make clean` in ocrd_all, like we do for `deps-ubuntu`. What do you think @stweil @bertsky

**Comment by stweil** [comment]
This is one of several nagging issues with the current build. Ideally running `make` should not change any of the submodules after they were checked out or at least restore them after building. Currently some files are modified, others are added:

	modified:   cor-asv-ann (untracked content)
	modified:   dinglehopper (untracked content)
	modified:   ocrd_anybaseocr (modified content, untracked content)
	modified:   ocrd_olahd_client (untracked content)
	modified:   ocrd_tesserocr (modified content, untracked content)
	modified:   sbb_textline_detector (untracked content)

**Comment by stweil** [comment]
@stefanCCS, these commands should help:

```
git -C ocrd_anybaseocr/ocrd_anybaseocr/pix2pixhd reset --hard
git -C ocrd_anybaseocr/ocrd_anybaseocr/pix2pixhd clean -fxd
touch ocrd_anybaseocr
```

**Comment by bertsky** [comment]
In this particular case, I think we can keep ocrd_all completely out of the picture: It was the non-existing packaging of pix2pixHD and the horrible integration of the pix2pixHD subcomponent in ocrd_anybaseocr which led us to this solution. But now that we need a proper [branch](https://github.com/NVIDIA/pix2pixHD/pull/293) for that anyway, why not apply our packaging patches in another branch, then merge both in an OCR-D fork's master, and refer to that?

(@kba if we can agree on this plan then I recommend transferring the issue to ocrd_anybaseocr, which I have no permissions for.)

**Comment by bertsky** [comment]
> It was the non-existing packaging of pix2pixHD and the horrible integration of the pix2pixHD subcomponent in ocrd_anybaseocr which led us to this solution. But now that we need a proper [branch](https://github.com/NVIDIA/pix2pixHD/pull/293) for that anyway, why not apply our packaging patches in another branch, then merge both in an OCR-D fork's master, and refer to that?

In that vein, I have created https://github.com/NVIDIA/pix2pixHD/pull/297, so we can rebase ocrd_anybaseocr on that.

**Comment by bertsky** [comment]
Alas, due to pypa/pip#6658, we cannot just make setup contain a pix2pixhd dependency as a relative path. So I think I'll just upload a pkg for it myself.

**Comment by bertsky** [comment]
Done: 
- fixed by https://github.com/OCR-D/ocrd_all/pull/304
- based on https://github.com/OCR-D/ocrd_anybaseocr/pull/91

**Comment by kba** [comment]
> So I think I'll just upload a pkg for it myself.

https://pypi.org/project/pix2pixhd/ :tada:

**Comment by kba** [comment]
> (@kba if we can agree on this plan then I recommend transferring the issue to ocrd_anybaseocr, which I have no permissions for.

I could but you solved everything AFAICS. Is there still a need for it?

**Comment by bertsky** [comment]
> I could but you solved everything AFAICS. Is there still a need for it?

No, not anymore.
