### ISSUE TITLE
Native installation - got exception during 'sudo make deps-ubuntu'

### ISSUE THREAD

**Issue by stefanCCS** [OCR-D/ocrd_all#321]
I have tried to setup a new system (native) on Ubuntu 22.04.
I have followed https://ocr-d.de/en/setup
There `sudo make deps-ubuntu` has thrown the following exception:
```
make deps-ubuntu-modules
make[1]: Entering directory '/home/ocrdadmin/ocrd_all'
fatal: unsafe repository ('/home/ocrdadmin/ocrd_all' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /home/ocrdadmin/ocrd_all
set -e; for dir in core; do make -C $dir deps-ubuntu PYTHON=python3; done
make[2]: Entering directory '/home/ocrdadmin/ocrd_all/core'
make[2]: *** No rule to make target 'deps-ubuntu'.  Stop.
make[2]: Leaving directory '/home/ocrdadmin/ocrd_all/core'
make[1]: *** [Makefile:784: deps-ubuntu-modules] Error 2
make[1]: Leaving directory '/home/ocrdadmin/ocrd_all'
make: *** [Makefile:768: deps-ubuntu] Error 2

```
--> please clarify

**Comment by cneud** [comment]
I've recently run into this as well, and because of the submodules, only this worked for me
`git config --global --add safe.directory "*"` (see also [here](https://marc.info/?l=git&m=164989570902912&w=2))

**Comment by kba** [comment]
Ah, right, the submodules. A little less drastic workaround than marking all directories as safe:

```
git config --global --add safe.directory '/path/to/ocrd_all
git config --global --add safe.directory '/path/to/monorepo/ocrd_all/*'
```

But really, the best solution will be to avoid calling `git submodule` as root.

**Comment by cneud** [comment]
> git config --global --add safe.directory '/path/to/monorepo/ocrd_all/*'

Have you tried? Because that did not solve it for me, only the global "*" did :(

**Comment by stweil** [comment]
Instead of requiring users to run `sudo make deps-ubuntu`, we could also add `sudo` only where necessary (`sudo apt-get install`). That would be needed in a number of submodules, so takes some time. Nevertheless I think that would be a good solution.

**Comment by bertsky** [comment]
> Instead of requiring users to run `sudo make deps-ubuntu`, we could also add `sudo` only where necessary (`sudo apt-get install`). That would be needed in a number of submodules, so takes some time. Nevertheless I think that would be a good solution.

That's ruled out because in CI we are already root, and `sudo` is not configured.

**Comment by stweil** [comment]
Running `sudo` from `root` either simpy works in CI or can be overridden for CI by using a macro or by providing a dummy `sudo` script.

**Comment by stweil** [comment]
It would also be possible to temporarily change the ownership of `.git`. That should also fix the problem

**Comment by bertsky** [comment]
@stweil at this point I would be fine with either fix.

**Comment by kba** [comment]
OK, so, possible solutions:

1. move the `sudo` call to the `deps-ubuntu` targets and make it an overrideable `SUDO` macro
2. temporarily change ownership of `.git` to root for `make deps-ubuntu`
3. generate the default `OCRD_MODULES` without using `git submodule status`, by
  a. parsing `.gitmodules` with grep etc.
  b. using the directory names as module names

Solution 1. is probably the cleanest, though I personally do not think it's a good idea to have `sudo` calls in the Makefile, we had that pattern in the beginning but then phased it out.

Solution 2. is likely the easiest fix but might lead to  strange bugs if the `make deps-ubuntu` call fails for whatever reason before the permisssions are changed back

Solution 3 is quite hacky but fairly easy to do.

So I would favor solution 3 but I am also open to solution 1.

**Comment by stweil** [comment]
Solution 3 looks nice but does not work for me: make runs `git submodule sync` which also fails.

**Comment by stweil** [comment]
This patch works for me (it includes code to parse `.gitmodules` which is not strictly needed):
```
stefan@bf0c7e312909:~/src/github/OCR-D/ocrd_all$ git diff
diff --git a/Makefile b/Makefile
index 5009ced..15f9898 100644
--- a/Makefile
+++ b/Makefile
@@ -73,7 +73,7 @@ DISABLED_MODULES ?= $(DEFAULT_DISABLED_MODULES)
 # opencv-python is only needed for aarch64-linux-gnu and other less common platforms,
 # so don't include it by default.
 ifeq ($(strip $(OCRD_MODULES)),)
-override OCRD_MODULES := $(filter-out $(DISABLED_MODULES),$(shell git submodule status | while read commit dir ref; do echo $$dir; done))
+override OCRD_MODULES := $(filter-out $(DISABLED_MODULES),$(shell grep ^.submodule .gitmodules | sed s/^.submodule..// | sed 's/".*//' | sort))
 endif
 
 # `all` is too much for a default, and `ocrd` is too little
@@ -764,6 +764,7 @@ clean-tesseract:
 # (in case deps-ubuntu has been used with sudo and some modules were updated)
 # install git and parallel first (which is required for the module updates)
 deps-ubuntu:
+       chown root . *
        apt-get -y install git parallel
 ifneq ($(suffix $(PYTHON)),)
 # install specific Python version in system via PPA
@@ -776,9 +777,7 @@ endif
        # Fix ownership of new/modified files and directories because
        # deps-ubuntu is run as root, but not in a Docker build were
        # it is not needed and costs a lot of time.
-       test "$$HOME" == "/" || chown -R --reference=$(CURDIR) .git $(OCRD_MODULES)
-# prevent the sem commands during above module updates from imposing sudo perms on HOME:
-       test "$$HOME" == "/" || chown -R --reference=$(HOME) $(HOME)/.parallel
+       test "$$HOME" == "/" || chown -R --reference=$(CURDIR)/.git .
 
 deps-ubuntu-modules:
        set -e; for dir in $^; do $(MAKE) -C $$dir deps-ubuntu PYTHON=$(PYTHON); done
```

**Comment by bertsky** [comment]
BTW, 1 (overriding `sudo`) entails modifying the independent `deps-ubuntu` rules in _all_ submodules – I'd rather not go down that path.

Since 3 is out, and 2 is making the existing workaround even uglier, and solution 0 (adding ocrd_all as a `safe.directory` in gitconf) is problematic, too: How about seizing the bull by the horn and (since we already rely on `sudo` for `apt` actions) use `sudo -u $(stat -c %u .) git ...` for all commands that do _not_ need priviledges under `deps-ubuntu` – and thus avoiding ownership changes completely?

**Comment by kba** [comment]
> How about seizing the bull by the horn and (since we already rely on `sudo` for `apt` actions) use `sudo -u $(stat -c %u .) git ...` for all commands that do _not_ need priviledges under `deps-ubuntu` – and thus avoiding ownership changes completely?

That solution (4) sounds great, because it's not really a workaround, it's sensible to run everything except those calls that explicitly require root on behalf of the user who actually owns the ocrd_all repo. I'll prepare a PR.

**Comment by stweil** [comment]
(4) is not a working solution, because `sudo` cannot be run by everybody.

**Comment by stefanCCS** [comment]
Using latest ocrd_all, and following standard setup procedure, I do not get anymore this exception during `sudo make deps-ubuntu` .
Therefore, fell free to close it ... (or should I close it?).

(bad news is, that I get an error during make all - see #327

**Comment by kba** [comment]
Yes, this particular issue is solved. On to the next one :)
