### ISSUE TITLE
Document Docker Hub installation

### ISSUE THREAD

**Issue by kba** [OCR-D/ocrd_all#33]
Also I have this neat table for what is available in {minim,medi,maxim}um that we could add to the README:

| Module                      | `minimum` | `medium` | `maximum` |
| -----                       | ----      | ----     | ----      |
| core                        | ☑         | ☑        | ☑         |
| ocrd_cis                    | ☑         | ☑        | ☑         |
| ocrd_im6convert             | ☑         | ☑        | ☑         |
| ocrd_repair_inconsistencies | ☑         | ☑        | ☑         |
| ocrd_tesserocr              | ☑         | ☑        | ☑         |
| tesserocr                   | ☑         | ☑        | ☑         |
| workflow-configuration      | ☑         | ☑        | ☑         |
| cor-asv-ann                 | -         | ☑        | ☑         |
| dinglehopper                | -         | ☑        | ☑         |
| format-converters           | -         | ☑        | ☑         |
| ocrd_calamari               | -         | ☑        | ☑         |
| ocrd_keraslm                | -         | ☑        | ☑         |
| ocrd_olena                  | -         | ☑        | ☑         |
| ocrd_segment                | -         | ☑        | ☑         |
| tesseract                   | -         | ☑        | ☑         |
| ocrd_anybaseocr             | -         | -        | ☑         |
| ocrd_kraken                 | -         | -        | ☑         |
| ocrd_ocropy                 | -         | -        | ☑         |
| ocrd_pc_segmentation        | -         | -        | ☑         |
| ocrd_typegroups_classifier  | -         | -        | ☑         |
| sbb_textline_detector       | -         | -        | ☑         |
| cor-asv-fst                 | -         | -        | ☑         |

**Comment by bertsky** [comment]
Yes, a quick overview is worth attending to changes in that configuration over time.

Maybe in a new subsection _Usage | Dockerhub images_? Also, we might add some CI and DH status images on top.

**Comment by kba** [comment]
> Maybe in a new subsection Usage | Dockerhub images? 

#34 

> Also, we might add some CI and DH status images on top.

CI status is no problem but DH badges are pretty useless IMHO. It's either "automated" (which isn't true here) or you can use the MicroBadger tools which actually have interesting stats (like number of layers, size, last update etc). but is cumbersome to set up with a WebHook after CI to notify that it should recalculate stuff etc. Not worth the effort I think.

**Comment by bertsky** [comment]
> CI status is no problem but DH badges are pretty useless IMHO.

Yes, but I think even showing `manual` (which isn't true either) is better than not showing dockerization at all...

> Not worth the effort I think.

Yeah sounds tricky

**Comment by kba** [comment]
> Yes, but I think even showing manual (which isn't true either) is better than not showing dockerization at all...

Done
