### ISSUE TITLE
sbb-binarize: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by jbarth-ubhd** [OCR-D/ocrd_all#348]
Dear reader,
tried sbb-textline (recommended on step 1),
got this error message:

```
  File "/usr/local/lib/python3.6/site-packages/sbb_binarize/sbb_binarize.py", line 270, in run
    img_last[:, :][img_last[:, :] > 0] = 255
TypeError: 'int' object is not subscriptable
```
(almost) complete workflow environment see https://digi.ub.uni-heidelberg.de/diglitData/v/duerer1527_-_aa.zip . Extracts to directory "aa". See run.sh and ocrd.log

ocrd.sif -> ocrd-2022-08-15.sif (not a newer one because https://github.com/OCR-D/ocrd_tesserocr/issues/189 )

**Comment by bertsky** [comment]
Should be transferred to [sbb_binarize](https://github.com/qurator-spk/sbb_binarization).

Probably one of the recent Numpy changes.

Which version of numpy and sbb_binarize is this?

**Comment by jbarth-ubhd** [comment]
[docker, 2022-08-15](https://hub.docker.com/layers/ocrd/all/2022-08-15/images/sha256-2f331331c342acb403a4d32ed17644393c94a1aa602959d3cbc3b8ca465cddba?context=explore)

**Comment by jbarth-ubhd** [comment]
```
> singularity exec -e ocrd.sif ocrd-sbb-binarize -V
Version 0.0.10, ocrd/core 2.38.0
```

**Comment by kba** [comment]
I cannot transfer issues across organisations, so I created https://github.com/qurator-spk/sbb_binarization/issues/57 manually. Best to continue discussion over there, so my QURATOR/MMK colleagues see this.
