### ISSUE TITLE
README: Update "conflicting requirements"

### ISSUE THREAD

**Issue by kba** [OCR-D/ocrd_all#35]
e.g. the pillow one should be gone.

ocrd_calamari is pushing for tf2 support.

When scrutinizing ocrd_anybaseocr this week, keep in mind to update if applicable.

**Comment by bertsky** [comment]
> ocrd_calamari is pushing for tf2 support.
> 
> When scrutinizing ocrd_anybaseocr this week, keep in mind to update if applicable.

That makes it urgent to isolate modules' venv from each other (but still integrate all executables into one PATH). I still have something half-ready, somewhere...

**Comment by stweil** [comment]
Can this be closed?

**Comment by bertsky** [comment]
Definitely!
