### ISSUE TITLE
Did-you-read-the-manual test?

### ISSUE THREAD

**Issue by jbarth-ubhd** [OCR-D/ocrd_all#350]
ocrd-cis-ocropy-deskew  -P **level-of-operation** ...

ocrd-tesserocr-deskew -P **operation_level** ...

is this divergence intenional?

**Comment by kba** [comment]
Historical reasons, mostly, due to different maintainers in the module project phase. We [did try to align parameters](https://github.com/OCR-D/spec/pull/136) but never got around to merge the spec/adapt the processors.

**Comment by bertsky** [comment]
> due to different maintainers in the module project phase

same developer, actually :-)

Carelessness, in combination with a lack of authority, or standardization effort. 

See https://github.com/OCR-D/spec/issues/134
