### ISSUE TITLE
Latest code fails to build all

### ISSUE THREAD

**Issue by stweil** [OCR-D/ocrd_all#37]
There are several issues with the current git master:

- `make all` tries to compile opencv-python although that is only needed for some architectures like ARM. Fix: PR #39.
- `make all` fails to build cor-asv-fst.
- `make all -k` does not continue with other modules after the failure with cor-asv-fst. Fix: PR #38.
- `make all` with a restricted list of modules (no cro-asv-fst) does not build ocrd-tesserocr-*. Fix: PR #38.

**Comment by stweil** [comment]
Related: issue #36.

**Comment by kba** [comment]
#38 and #39 should fix this.
