### ISSUE TITLE
Docker: build CD images sequentially

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd_all#417]
Currently we build minimum, medium, maximum and maximum-cuda in parallel.

Except for the latter, this offers no time advantage, just consumes more resources (credits).

I suggest we change to
- medium using minimum as first stage
- maximum using medium as first stage

and have the respective jobs depend on each other in the CI.

**Comment by stweil** [comment]
The [latest Docker build fails with a timeout](https://app.circleci.com/pipelines/github/OCR-D/ocrd_all/1066/workflows/36581dca-6fc2-41f1-90e6-1b57b4c3548b). Shouldn't the maximum builds now be faster than before because they only have to build on top of medium?
