### ISSUE TITLE
Broken builds on Ubuntu 20.04 

### ISSUE THREAD

**Issue by stweil** [OCR-D/ocrd_all#437]
`make all` succeeds, but `make check` fails for any Python version:

```
[...]
&&  { /home/runner/work/ocrd_all/ocrd_all/venv/sub-venv/headless-tf1/bin/cor-asv-ann-repl --help >/dev/null 2>&1 || /home/runner/work/ocrd_all/ocrd_all/venv/sub-venv/headless-tf1/bin/cor-asv-ann-repl -h >/dev/null; }
. /home/runner/work/ocrd_all/ocrd_all/venv/sub-venv/headless-tf1/bin/activate && pip check
scikit-image 0.21.0 has requirement imageio>=2.27, but you have imageio 2.14.1.
scikit-image 0.21.0 has requirement tifffile>=2022.8.12, but you have tifffile 2021.11.2.
make[1]: *** [Makefile:737: check] Error 1
[...]
```

**Comment by stweil** [comment]
See results from a [complete test matrix](https://github.com/stweil/ocrd_all/actions/runs/9234310092/job/25407825629).

All builds with Ubuntu 20.04 fail with the error above, Ubuntu 24.04 fails because it requires https://github.com/OCR-D/ocrd_tesserocr/pull/211, Ubuntu 22.04 works fine.

**Comment by bertsky** [comment]
So there's a new scikit-image, the dependencies of which are in conflict with some of ours. 

Who is it that wants (and holds) imageio and tifffile here?

**Comment by stweil** [comment]
cor-asv-ann?
