### ISSUE TITLE
make CI config more robust to network

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd_all#45]
Currently CircliCI fails in `deploy` job due to network connectivity problems during `pip install`. Dockerfile already has `--timeout=3000` among the options for pip. Still, we get:

    Connection broken: ConnectionResetError(104, 'Connection reset by peer')

Should we increase the timeout? Or is this just a bad day?

**Comment by kba** [comment]
Tough to do something sensible about something so unpredictable. Maybe something like `make foo || (sleep 60;echo "Failed once, waiting 60 seconds, trying again"; make foo)` to just repeat steps? Ugly as hell but if the network is just gone for more then a few seconds it might help.

**Comment by kba** [comment]
I restarted the build. @stweil @bertsky Do you have the rights to do that yourself at https://circleci.com/gh/OCR-D/workflows/ocrd_all ?

**Comment by stweil** [comment]
I don't have the rights.

**Comment by bertsky** [comment]
fixed as of #77
