### ISSUE TITLE
Add ocrd_fileformat

### ISSUE THREAD

**Issue by kba** [OCR-D/ocrd_all#80]

**Comment by bertsky** [comment]
And https://github.com/JKamlah/ocrd_pagetopdf

**Comment by kba** [comment]
> And https://github.com/JKamlah/ocrd_pagetopdf

Cf https://github.com/OCR-D/ocrd_all/issues/78 But really, I would prefer to have ocrd_pagetopdf as part of ocr-fileformat.

**Comment by bertsky** [comment]
> Cf #78 But really, I would prefer to have ocrd_pagetopdf as part of ocr-fileformat.

right – sorry for the noise!
