### ISSUE TITLE
make all fails to build on ubuntu 20.04 due to missing tensorflow-gpu version for Python 3.8

### ISSUE THREAD

**Issue by cneud** [OCR-D/ocrd_all#89]
``make all`` (after ``sudo make deps-ubuntu``) using [c3255b](https://github.com/OCR-D/ocrd_all/tree/dc3255b322ac7a6eac85cfa9ea52b55cb049ca29) on Ubuntu 20.04/Python 3.8 fails to build due to missing tensorflow version 1.15.* - ~[pypi](https://pypi.org/project/tensorflow-gpu/#history) has 1.15.0 and 1.15.2 available though~ (edit: only for older Python versions)

```
Successfully built ocrd
Installing collected packages: ocrd
Successfully installed ocrd-2.5.3
make[1]: Leaving directory '/home/cnd/ocrd_all/core'
[...]
. /home/cnd/ocrd/bin/activate && cd cor-asv-ann && pip3 install  .
Processing /home/cnd/ocrd_all/cor-asv-ann
Requirement already satisfied: ocrd>=2.0 in /home/cnd/ocrd/lib/python3.8/site-packages (from ocrd-cor-asv-ann==0.1.2) (2.5.3)
Requirement already satisfied: click in /home/cnd/ocrd/lib/python3.8/site-packages (from ocrd-cor-asv-ann==0.1.2) (7.1.2)
Collecting keras==2.3.*
  Downloading Keras-2.3.1-py2.py3-none-any.whl (377 kB)
     |████████████████████████████████| 377 kB 443 kB/s 
Requirement already satisfied: numpy in /home/cnd/ocrd/lib/python3.8/site-packages (from ocrd-cor-asv-ann==0.1.2) (1.18.4)
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.15.* (from ocrd-cor-asv-ann==0.1.2) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4)
ERROR: No matching distribution found for tensorflow-gpu==1.15.* (from ocrd-cor-asv-ann==0.1.2)
make: *** [Makefile:185: /home/cnd/ocrd/bin/ocrd-cor-asv-ann-evaluate] Error 1
```

**Comment by kba** [comment]
There is [no version of tensorflow-gpu for py38](https://pypi.org/project/tensorflow-gpu/1.15.2/#files) though, that is the issue here IIUC.

**Comment by cneud** [comment]
@kba Well spotted! Just edited the issue to include Python version = 3.8.

**Comment by kba** [comment]
Unless the tensorflow people decide to backport 3.8 support for 1.15.*, I see little we can do unfortunately, except upgrade the code to use tf 2.2+.

**Comment by cneud** [comment]
> Yup, tensorflow supports python 3.8 only for 2.2.+

Ok so for 20.04 then we have to wait whether tf will provide packages of 1.15.* also with support for Python 3.8.

**Comment by cneud** [comment]
> except upgrade the code to use tf 2.2+.

Yup, another reason to migrate to tf2.x. 

I am closing this now, but we should probably make supported Python versions known in the docs.

**Comment by bertsky** [comment]
> Ok so for 20.04 then we have to wait whether tf will provide packages of 1.15.* also with support for Python 3.8.

Either that or [build TF](https://www.tensorflow.org/install/gpu) yourself. (Be warned though: it takes ages and often does not work out of the box, esp. on new platforms.)

**Comment by bertsky** [comment]
> Yup, another reason to migrate to tf2.x.

I don't think this is coming any time soon for some of our modules. TF made it really hard to port some ways of writing optimisers etc. And they keep making major modifications even within TF2. Plus all models will have to be re-trained.

**Comment by cneud** [comment]
> build TF yourself

Will have to anyway for qurator ;)
