### ISSUE TITLE
leptonica dependency for tesseract - compile and/or deps-ubuntu?

### ISSUE THREAD

**Issue by kba** [OCR-D/ocrd_all#99]
I'm [installing ocrd_all in a fresh WSL Ubuntu 18.04 instance](https://github.com/OCR-D/ocrd-website/wiki/OCR-D-on-Windows). I notice that missing `libleptonica-dev` prevents tesseract compilation and is not installed with `sudo make deps-ubuntu`. Running `sudo apt-get install libleptonica-dev` remedies this for me.

`tesseract` is in `OCRD_MODULES` according to `make show` but `CUSTOM_DEPS` does not contain `libleptonica-dev` when running `make deps-ubuntu`.

Since it does work for the docker builds as it is supposed to, what am I doing wrong here?

**Comment by stweil** [comment]
Do you have a private `local.mk` which overrides `CUSTOM_DEPS`? IT works for me locally:

    make deps-ubuntu -n
    [...]
    apt-get -y install unzip wget python3-venv  g++ make automake libleptonica-dev libarchive-dev libcurl4-nss-dev libgif-dev libjpeg-dev libpng-dev libtiff-dev

**Comment by kba** [comment]
Thanks Stefan. Strangely enough, it does work now as expected, no idea why it did not before.

Sorry for the noise.
